export enum GroupMemberPositionChangeEnum {
    ACCEPT_RECEIVED_INVITATION = 'ACCEPT_RECEIVED_INVITATION',
    REMOVE_RECEIVED_INVITATION = 'REMOVE_RECEIVED_INVITATION',
    REMOVE_SENT_INVITATION = 'REMOVE_SENT_INVITATION',
    REMOVE_MEMBER = 'REMOVE_MEMBER',
    SET_AS_MANAGER = 'SET_AS_MANAGER',
    REMOVE_MANAGER = 'REMOVE_MANAGER',
    SET_AS_OWNER = 'SET_AS_OWNER',
}


