import {NgModule} from '@angular/core';
import {
    DefaultImgDirective,
    DisableControlDirective,
    DropzoneDirective,
    RecommendationDirective,
    ScrollOffsetDirective,
    TooltipDirective
} from './directives';
import {
    ArticleCardsComponent,
    ClickableNameItemComponent,
    FinancialChartComponent,
    FixedRangeSliderComponent,
    GaugeChartComponent,
    GenericCardComponent,
    GenericChartComponent,
    GenericExtensionPanelComponent,
    GenericFadingCardContentComponent,
    GenericFancyCardComponent,
    GenericListComponent,
    InlineModificationFormComponent,
    PieChartWrapperComponent,
    PositionChangeItemComponent,
    PriceChangeItemComponent,
    PriceCompareItemComponent,
    RangeRatingSliderComponent,
    SearchWrapperComponent,
    StockInfoIdentificationItemComponent,
    TableHighLowRangeComponent,
    TableIncreasingItemComponent,
    TitleWithLogoItemComponent,
    UploaderComponent,
    UploadTaskComponent
} from './components';
import {
    ChartKeyValueFormatterPipe,
    HoldingsTotalInvestedPipe,
    IncreasePrctPipe,
    NumberFormatterPipe,
    ObjNgForPipe,
    RelativeTimePipe,
    ReverseArrayPipe,
    SplitKeyToTitlecasePipe,
    SplitPipe,
    SumUpPipe,
    TypeofPipe
} from './pipes';
import {FinancialChartContainerComponent, HeaderComponent, StockSummaryContainerComponent} from './containers';
import {
    ConfirmationPopOverComponent,
    FinancialChartModalComponent,
    InlineInputPopUpComponent,
    OptionPickerPopOverComponent
} from './entry-components';
import {SharedProvidersModule} from './shared-providers.module';
import {ListSkeletonComponent} from './components/lists';
import {SharedMaterialModule} from './shared-material.module';


@NgModule({
    declarations: [
        FixedRangeSliderComponent,
        DefaultImgDirective,
        FinancialChartComponent,
        GaugeChartComponent,
        NumberFormatterPipe,
        RelativeTimePipe,
        SumUpPipe,
        HeaderComponent,
        InlineModificationFormComponent,
        GenericChartComponent,
        GenericCardComponent,
        FinancialChartContainerComponent,
        PriceCompareItemComponent,
        InlineInputPopUpComponent,
        DropzoneDirective,
        UploaderComponent,
        UploadTaskComponent,
        PriceChangeItemComponent,
        ClickableNameItemComponent,
        GenericListComponent,
        TitleWithLogoItemComponent,
        TooltipDirective,
        SearchWrapperComponent,
        ScrollOffsetDirective,
        GenericFancyCardComponent,
        ObjNgForPipe,
        GenericFadingCardContentComponent,
        TableHighLowRangeComponent,
        RecommendationDirective,
        ArticleCardsComponent,
        StockInfoIdentificationItemComponent,
        FinancialChartModalComponent,
        StockSummaryContainerComponent,
        HoldingsTotalInvestedPipe,
        RangeRatingSliderComponent,
        TableIncreasingItemComponent,
        SplitKeyToTitlecasePipe,
        SplitPipe,
        DisableControlDirective,
        PositionChangeItemComponent,
        OptionPickerPopOverComponent,
        ConfirmationPopOverComponent,
        ListSkeletonComponent,
        ReverseArrayPipe,
        TypeofPipe,
        IncreasePrctPipe,
        GenericExtensionPanelComponent,
        ChartKeyValueFormatterPipe,
        PieChartWrapperComponent
    ],
    imports: [
        SharedProvidersModule,
        SharedMaterialModule,

    ],
    exports: [
        SharedProvidersModule,
        FixedRangeSliderComponent,
        DefaultImgDirective,
        GaugeChartComponent,
        NumberFormatterPipe,
        RelativeTimePipe,
        SumUpPipe,
        HeaderComponent,
        InlineModificationFormComponent,
        GenericChartComponent,
        GenericCardComponent,
        FinancialChartContainerComponent,
        PriceCompareItemComponent,
        InlineInputPopUpComponent,
        UploaderComponent,
        UploadTaskComponent,
        PriceChangeItemComponent,
        ClickableNameItemComponent,
        GenericListComponent,
        TitleWithLogoItemComponent,
        TooltipDirective,
        SearchWrapperComponent,
        GenericFancyCardComponent,
        ObjNgForPipe,
        GenericFadingCardContentComponent,
        TableHighLowRangeComponent,
        RecommendationDirective,
        ArticleCardsComponent,
        StockInfoIdentificationItemComponent,
        FinancialChartModalComponent,
        StockSummaryContainerComponent,
        HoldingsTotalInvestedPipe,
        RangeRatingSliderComponent,
        TableIncreasingItemComponent,
        SplitKeyToTitlecasePipe,
        SplitPipe,
        DisableControlDirective,
        PositionChangeItemComponent,
        OptionPickerPopOverComponent,
        ConfirmationPopOverComponent,
        ListSkeletonComponent,
        ReverseArrayPipe,
        TypeofPipe,
        IncreasePrctPipe,
        GenericExtensionPanelComponent,
        ChartKeyValueFormatterPipe,
        PieChartWrapperComponent,
        SharedMaterialModule
    ],
    entryComponents: [
        InlineInputPopUpComponent,
        OptionPickerPopOverComponent
    ]
})
export class SharedModule {
}
