version: "3.8"

services: 
    graphql:
        build: ./graphql
        container_name: graphql
        restart: always
        environment:
            - PORT=18081
        expose: 
            - 18081
        networks:
            - stock_tracker_network

    flask:
        build: ./flask
        container_name: flask
        restart: always
        volumes:
            - ./flask:/app
        environment: 
            - APP_NAME=MyFlaskApp
        expose: 
            - 18080
        networks:
            - stock_tracker_network
    
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports: 
            - "5001:5001"
        networks:
            - stock_tracker_network

networks:
    stock_tracker_network:
        driver: bridge